ITS-3328 Redirect from TechnicalErrorController try again option dyna…
hmrc/find-your-national-insurance-number-frontend pull request #143
Opened 2024-02-13 15:43 UTC by Kitkatann

…mically based on if postcode is present

2024-02-13 15:54 UTC, Kitkatann commented on app/controllers/TechnicalErrorController.scala
> +            if (value.toString == "tryAgain") {
Yep that makes it clearer, will do

2024-02-13 16:02 UTC, Kitkatann commented on app/controllers/TechnicalErrorController.scala
> +            if (value.toString == "tryAgain") {
Leaving as is since it ends up about the same complexity with all the variables that would need passing through to the proposed method

2024-02-13 16:58 UTC, ajchilts requested changes
One small simplification.

2024-02-13 16:58 UTC, ajchilts commented on app/controllers/TechnicalErrorController.scala
> +            val postcode: String = personalDetails.map(_.postCode.getOrElse(StringUtils.EMPTY)).getOrElse(StringUtils.EMPTY)
This could be simplified a little 

`val postcode: String = personalDetails.flatMap(_.postCode).getOrElse(StringUtils.EMPTY)`

2024-02-15 16:05 UTC, ajchilts approved these changes
LGTM

2024-02-15 16:26 UTC, ajchilts approved these changes

2024-02-15 16:26 UTC, merged