Adding a check so the idData connector data does not call the id serv…
hmrc/find-your-national-insurance-number-frontend pull request #163
Opened 2024-03-01 07:24 UTC by rishisachania

…ice when there is no NINO from PDV

2024-03-01 09:20 UTC, ajchilts commented on app/connectors/IndividualDetailsConnector.scala
> +      IndividualDetailsResponseEnvelope(Left(ConnectorError(400, "Cannot call getIndividualDetails with an empty identifier")))
I am assuming that this is handled by the caller and the block correctly routes based on the fact this was not matched?

2024-03-01 09:22 UTC, ajchilts commented on app/connectors/IndividualDetailsConnector.scala
> +      IndividualDetailsResponseEnvelope(Left(ConnectorError(400, "Cannot call getIndividualDetails with an empty identifier")))
Also do we need to add a test for this?

2024-03-06 11:59 UTC, ajchilts requested changes

2024-03-06 11:59 UTC, ajchilts commented on app/connectors/IndividualDetailsConnector.scala
> +      IndividualDetailsResponseEnvelope(Left(ConnectorError(400, "Cannot call getIndividualDetails with an empty identifier")))
@rishisachania  @rambabu-posa  - the more I think about this the more I do not like this approach. This is not a connector error. It's not an error at all. It's simply that we do not want to attempt to make this call if we have no Nino. Triggering an error is misleading and I think we need a different approach. Let me think about this.

2024-03-06 12:06 UTC, rambabu-posa commented
@ajchilts  Is it good to handle it at first step in Controller?

2024-03-06 13:33 UTC, ajchilts commented
@rambabu-posa  - I think we need to omit the call if we do not need to make it. This is proving difficult with the way that the code is written as it expects either an error of individuals details. When in reality it's OK to have non matched and no individuals details.

2024-03-12 10:34 UTC, ajchilts approved these changes

2024-03-12 10:42 UTC, merged